language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-16

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    
    # run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
