language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  artifacts:
    debug: true
    key: AKIAJ7PERFIVVPEHXOVA
    secret: rvTPS9HzCQddg1Xg3yeDVBtzDxk9bsVwffViAra
    bucket: travisci-logs
    s3_region: us-west-2
