language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  artifacts:
    debug: true
    paths:
      - /home/travis/build/fit360/spott/app/build/outputs/lint-results.html
    key: AKIAJ7PERFIVVPEHXOVA
    secret: rvTPS9HzCQddg1Xg3yeDVBtzDxk9bsVwffViAra
    bucket: travisci-logs
    s3_region: us-west-2
